In [ ]:
import pandas as pd
import numpy as np
import scipy as sp
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('StudentsPerformance.csv')

In [ ]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0
1,female,group C,some college,standard,completed,69.0,90.0,88.0
2,female,group B,master's degree,standard,none,90.0,95.0,93.0
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,NaN
4,male,group C,some college,standard,none,76.0,78.0,75.0
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99.0,95.0
996,male,group C,high school,free/reduced,none,62.0,55.0,55.0
997,female,group C,high school,free/reduced,completed,59.0,71.0,65.0
998,female,group D,some college,standard,completed,68.0,78.0,77.0
999,female,group D,some college,free/reduced,none,77.0,86.0,86.0

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
df.dtypes

gender                          object
race/ethnicity                  object
parental level of education     object
lunch                           object
test preparation course         object
math score                     float64
reading score                  float64
writing score                  float64
dtype: object

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     6
reading score                  6
writing score                  3
dtype: int64

In [ ]:
from numpy._core.fromnumeric import mean
outliers = []
def detect(df):
  threshold=3
  mean=np.mean(df)
  std=np.std(df)

  for d in df:
    z_score=(d-mean)/std
    if np.abs(z_score)>threshold:
      outliers.append(d)
  return outliers

In [ ]:
var ="math score"
#var="reading score"
#var="writing score"

In [ ]:
z_score=detect(df[var])

In [ ]:
outliers=df[df[var].isin(z_score)]

In [ ]:
outliers

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
7,male,group B,some college,free/reduced,none,120.0,43.0,39.0
17,female,group B,some high school,free/reduced,none,18.0,32.0,28.0
39,male,group B,associate's degree,free/reduced,none,10.0,56.0,57.0
59,female,group C,some high school,free/reduced,none,0.0,17.0,10.0
113,female,group D,some college,standard,none,1.0,58.0,54.0
139,male,group D,some college,standard,completed,200.0,61.0,69.0
980,female,group B,high school,free/reduced,none,8.0,24.0,23.0

In [ ]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [ ]:
series = pd.isnull(df["math score"])
df[series]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
12,female,group B,high school,standard,none,NaN,81.0,73.0
93,male,group C,associate's degree,free/reduced,completed,NaN,45.0,50.0
493,female,group C,bachelor's degree,standard,none,NaN,88.0,90.0
647,female,group E,high school,free/reduced,none,NaN,62.0,68.0
923,female,group B,associate's degree,free/reduced,none,NaN,65.0,65.0
943,male,group A,some high school,free/reduced,completed,NaN,62.0,61.0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])
newdf=df
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,group B,bachelor's degree,standard,none,72.0,72.0,74.0
1,0,group C,some college,standard,completed,69.0,90.0,88.0
2,0,group B,master's degree,standard,none,90.0,95.0,93.0
3,1,group A,associate's degree,free/reduced,none,47.0,57.0,NaN
4,1,group C,some college,standard,none,76.0,78.0,75.0
...,...,...,...,...,...,...,...,...
995,0,group E,master's degree,standard,completed,88.0,99.0,95.0
996,1,group C,high school,free/reduced,none,62.0,55.0,55.0
997,0,group C,high school,free/reduced,completed,59.0,71.0,65.0
998,0,group D,some college,standard,completed,68.0,78.0,77.0
999,0,group D,some college,free/reduced,none,77.0,86.0,86.0

In [ ]:
missing_values = ["Na", "na"]

In [ ]:
df = pd.read_csv("StudentsPerformance.csv", na_values=missing_values)
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0
1,female,group C,some college,standard,completed,69.0,90.0,88.0
2,female,group B,master's degree,standard,none,90.0,95.0,93.0
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,NaN
4,male,group C,some college,standard,none,76.0,78.0,75.0
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99.0,95.0
996,male,group C,high school,free/reduced,none,62.0,55.0,55.0
997,female,group C,high school,free/reduced,completed,59.0,71.0,65.0
998,female,group D,some college,standard,completed,68.0,78.0,77.0
999,female,group D,some college,free/reduced,none,77.0,86.0,86.0